### ISSUE TITLE
Maven build with Oracle Java 22 failed because of missing dependencies for JavaFX

### ISSUE THREAD

**Issue by OlexYarm** [harryssuperman/javafxtutorial#2]
I had to add following dependencies in pom.xml file to successfully build project with Oracle Java 22.

<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>23-ea+22</version>
</dependency>

<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-fxml</artifactId>
    <version>23-ea+22</version>
</dependency>
        

<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-web</artifactId>
    <version>23-ea+22</version>
</dependency>

**Comment by harryssuperman** [comment]
@OlexYarm Thanks for the comment. I will include in the README.md that a JDK with JavaFX like Zulu or Liberica will be needed. Also the option in pom as dependencies if a jdk without JavaFX is running.
